[programs.localnet]
quick_question = "3nwtVSUXMNeFYDA4dXrSLb8qYwMXwm1CaEoho5PRW2aH"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/colbyharrison/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
